// Minimalist Secure Workspace - permukaan UI bersama: brand, dialog sensitif, salin, TOTP, dan status kebijakan.
import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { toast } from "sonner";
import { Check, Copy, LogIn, LogOut, ShieldCheck, Trash2, X } from "lucide-react";
import { getTotpCode } from "@/lib/vault";
import { getToastDuration } from "@/lib/vault-helpers";
export function Logo() { return <div className="brand-lockup flex items-center gap-3"><img src="/assets/vaultmark-logo.svg" className="brand-mark size-9 rounded-xl" alt="Vaultmark" /><div><div className="brand-wordmark font-display text-[15px] font-semibold tracking-[-.03em]">vaultmark</div><div className="brand-subline text-[10px] font-medium uppercase tracking-[.18em] text-slate-400">private workspace</div></div></div>; }
export function useFocusTrap(active: boolean, onEscape?: () => void) { const ref = useRef<HTMLDivElement>(null); useEffect(() => { if (!active) return; const root = ref.current; if (!root) return; const selector = 'button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])'; const getFocusable = () => Array.from(root.querySelectorAll<HTMLElement>(selector)); const first = getFocusable()[0]; first?.focus(); const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") { event.preventDefault(); onEscape?.(); return; } if (event.key !== "Tab") return; const items = getFocusable(); if (!items.length) return; const current = document.activeElement; const firstItem = items[0]; const lastItem = items[items.length - 1]; if (event.shiftKey && current === firstItem) { event.preventDefault(); lastItem.focus(); } else if (!event.shiftKey && current === lastItem) { event.preventDefault(); firstItem.focus(); } }; document.addEventListener("keydown", onKeyDown); return () => document.removeEventListener("keydown", onKeyDown); }, [active, onEscape]); return ref; }
export function ConfirmDialog({ title, message, confirmLabel, tone = "default", onClose, onConfirm }: { title: string; message: string; confirmLabel: string; tone?: "default" | "danger"; onClose: () => void; onConfirm: () => void }) { const dialogRef = useFocusTrap(true, onClose); return <div className="modal-backdrop compact-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><div ref={dialogRef} className="modal-card confirm-card" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><div className="flex items-start gap-3"><div className={`confirm-mark ${tone === "danger" ? "danger" : ""}`}>{tone === "danger" ? <Trash2 className="size-4" /> : <LogIn className="size-4" />}</div><div className="min-w-0"><h2 id="confirm-title" className="font-display text-lg font-semibold tracking-[-.03em] text-slate-900">{title}</h2><p className="mt-1 text-sm leading-5 text-slate-500">{message}</p></div><button className="icon-button action-tooltip ml-auto shrink-0" data-tooltip="Tutup" aria-label="Tutup dialog" onClick={onClose}><X className="size-4" /></button></div><div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={onClose}>Batal</Button><Button className={tone === "danger" ? "bg-rose-500 text-white hover:bg-rose-600" : "bg-[#1FACFF] text-white hover:bg-[#0D8DDB]"} onClick={onConfirm}>{confirmLabel}</Button></div></div></div>; }
export function CopyButton({ value, label }: { value: string; label: string }) { const [copied, setCopied] = useState(false); return <button title={`Salin ${label}`} onClick={async () => { await navigator.clipboard.writeText(value); setCopied(true); toast.success(`${label} berhasil disalin`, { description: label === "password" ? "Password tersalin. Clipboard akan dibersihkan dalam 12 detik." : "Clipboard akan dibersihkan dalam 12 detik.", duration: getToastDuration() }); setTimeout(() => { navigator.clipboard.writeText("").catch(() => undefined); setCopied(false); }, 12000); }} className="icon-button action-tooltip" data-tooltip={`Salin ${label}`} aria-label={`Salin ${label}`}>{copied ? <Check className="size-4 text-emerald-500" /> : <Copy className="size-4" />}</button>; }
export function Totp({ secret }: { secret?: string }) { const [now, setNow] = useState(Date.now()); useEffect(() => { const id = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(id); }, []); if (!secret) return null; const remain = 30 - Math.floor((now / 1000) % 30); const code = getTotpCode(secret) ?? "------"; return <div className="totp-card"><div className="totp-inline"><span className="totp-label">2FA</span><span className="font-mono text-sm font-semibold tracking-[.16em] text-slate-800">{code}</span><span className="totp-remaining">{remain}s</span><CopyButton value={code} label="kode 2FA" /></div><Progress value={(remain / 30) * 100} className="mt-1 h-1 bg-[#D9F0FF] [&>div]:bg-[#1FACFF]" /></div>; }
export function SecurityPolicyUnavailable({ message, onRetry, onLogout }: { message: string; onRetry: () => void; onLogout: () => void }) { return <main className="lock-shell"><Logo /><div className="lock-card password-change-card"><div className="mx-auto flex size-16 items-center justify-center rounded-3xl bg-[#FFF3E8]"><ShieldCheck className="size-7 text-[#D97706]" /></div><div className="eyebrow mt-7">security policy unavailable</div><h1 className="mt-3 font-display text-3xl font-semibold tracking-[-.05em]">Kebijakan keamanan belum siap.</h1><p className="mt-3 text-sm leading-6 text-slate-500">Vault tetap dikunci sampai policy akun berhasil dibaca dari Firestore. Password dan data vault tidak dilewati atau disimpan lokal.</p><p className="mt-4 text-sm font-medium leading-6 text-rose-600" role="alert">{message}</p><Button className="mt-6 h-12 w-full bg-[#1FACFF] text-white hover:bg-[#0D8DDB]" onClick={onRetry}>Coba lagi</Button><button type="button" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-slate-900" onClick={onLogout}><LogOut className="size-4" /> Logout</button></div></main>; }